name: 'Run Tests'
on:
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  python-code-quality-checks:
    name: 'Code Quality Checks'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: 'Install Poetry'
        uses: Gr1N/setup-poetry@v9
      - name: 'Build kmultiversx'
        run: make kmultiversx
      - name: 'Run code quality checks'
        run: make -C kmultiversx check

  tests:
    runs-on: [self-hosted, linux, normal]
    name: 'Tests'
    timeout-minutes: 45
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: 'Set up Docker'
        uses: ./.github/actions/with-docker
        with:
          container-name: elrond-semantics-ci-${{ github.sha }}
      - name: 'Build kmultiversx'
        run: docker exec -t elrond-semantics-ci-${GITHUB_SHA} make kmultiversx
      - name: 'Build K definitions'
        run: docker exec -t elrond-semantics-ci-${GITHUB_SHA} make build-mandos build-kasmer
      - name: 'KMultiversX Tests'
        run: docker exec -t elrond-semantics-ci-${GITHUB_SHA} make -C kmultiversx test
      - name: 'Simple Tests'
        run: docker exec -t elrond-semantics-ci-${GITHUB_SHA} make test-simple -j6
      - name: 'Mandos Tests'
        run: docker exec -t elrond-semantics-ci-${GITHUB_SHA} make mandos-test -j6
      - name: 'TestApi tests'
        run: docker exec -t elrond-semantics-ci-${GITHUB_SHA} make test-testapi
      - name: 'Contract Test: Adder'
        run: docker exec -t elrond-semantics-ci-${GITHUB_SHA} make test-elrond-adder
      - name: 'Contract Test: Crowdfunding ESDT'
        run: docker exec -t elrond-semantics-ci-${GITHUB_SHA} make test-elrond-crowdfunding-esdt
      - name: 'Contract Test: Multisig'
        run: docker exec -t elrond-semantics-ci-${GITHUB_SHA} make test-elrond-multisig
      - name: 'Contract Test: NFT Minter'
        run: docker exec -t elrond-semantics-ci-${GITHUB_SHA} make test-elrond-nft-minter
      - name: 'Contract Tests: Custom'
        run: docker exec -t elrond-semantics-ci-${GITHUB_SHA} make test-custom-contracts
      - name: 'Tear down Docker'
        if: always()
        run: |
          docker stop --time=0 elrond-semantics-ci-${GITHUB_SHA}

  feature-tests:
    runs-on: [self-hosted, linux, normal]
    name: 'Feature Tests'
    timeout-minutes: 45
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: 'Set up Docker'
        uses: ./.github/actions/with-docker
        with:
          container-name: elrond-semantics-ci-${{ github.sha }}
      - name: 'Build kmultiversx'
        run: docker exec -t elrond-semantics-ci-${GITHUB_SHA} make kmultiversx
      - name: 'Build K definition'
        run: docker exec -t elrond-semantics-ci-${GITHUB_SHA} make build
      - name: 'Feature Test: Basic'
        run: docker exec -t elrond-semantics-ci-${GITHUB_SHA} make test-elrond-basic-features -j6
      - name: 'Feature Test: Alloc'
        run: docker exec -t elrond-semantics-ci-${GITHUB_SHA} make test-elrond-alloc-features -j6
      - name: 'Feature Test: Composability'
        run: docker exec -t elrond-semantics-ci-${GITHUB_SHA} make test-elrond-composability-features -j6
      - name: 'Tear down Docker'
        if: always()
        run: |
          docker stop --time=0 elrond-semantics-ci-${GITHUB_SHA}
